name: AttackIndicator
version: '2.2'
main: org.eneryleen.attackIndicator.AttackIndicator
api-version: '1.13'
authors: [ Eneryleen ]

commands:
  attackindicator:
    description: AttackIndicator main command
    usage: /attackindicator <reload>
    aliases: [ ai ]

permissions:
  attackindicator.reload:
    description: Allows reloading the plugin configuration
    default: op
